- user: av
  hosts: all
  gather_facts: no
  vars:
    release_dir: /home/av/smppex_web/{{local_release_dir}}
    current_dir: /home/av/smppex_web/current

  tasks:
  - file: path={{ release_dir }} state=directory

  - unarchive: src=../{{ local_release_dir }}/smppex_web.tar.gz dest={{release_dir}} creates=yes

  - file:
      src: "{{release_dir}}/smppex_web"
      dest: "{{ current_dir }}"
      state: link

  - file: path={{ current_dir }}/log state=directory

  - command: dpkg-query -W elixir
    register: elixir_check_deb
    failed_when: elixir_check_deb.rc > 1
    changed_when: elixir_check_deb.rc == 1

  - get_url: url=https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb dest=/tmp/erlang-solutions_1.0_all.deb
    when: elixir_check_deb.rc == 1

  - apt: deb=/tmp/erlang-solutions_1.0_all.deb
    become: yes
    when: elixir_check_deb.rc == 1

  - apt: update_cache=yes
    become: yes
    when: elixir_check_deb.rc == 1

  - apt: name=elixir state=present
    become: yes
    when: elixir_check_deb.rc == 1

  - shell: mix local.hex --force
    when: elixir_check_deb.rc == 1

  - file:
      src: "{{ current_dir }}/deploy/smppex_web.service"
      dest: /etc/systemd/system/smppex_web.service
      state: link
    become: yes

  - file:
      src: "{{ current_dir }}/deploy/smppex.rubybox.ru.conf"
      dest: /etc/nginx/sites-available/smppex.rubybox.ru.conf
      state: link
    become: yes

  - file:
      src: /etc/nginx/sites-available/smppex.rubybox.ru.conf
      dest: /etc/nginx/sites-enabled/smppex.rubybox.ru.conf
      state: link
    become: yes

  - service: name=nginx state=restarted enabled=yes
    become: yes

  - shell: systemctl daemon-reload
    become: yes

  - shell: systemctl restart smppex_web
    become: yes

